apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: processcube-sample-app

resources:
  - ../../base

patches:
  - target:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: processcube-gateway
    path: ./gateway-patch.yml
  - target:
      group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: engine
    path: ./engine/httproute-patch.yml
  - target:
      group: apps
      kind: Deployment
      name: engine
    path: ./engine/deployment-patch.yml
  - target:
      group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: authority
    path: ./authority/httproute-patch.yml
  - target:
      group: apps
      kind: Deployment
      name: nodered
    path: ./lowcode/deployment-patch.yml
  - target:
      group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: nodered
    path: ./lowcode/httproute-patch.yml


configMapGenerator:
  - name: authority-config
    behavior: replace
    files:
      - ./authority/config.json